---
title: "Building R Packages"
output: html_notebook
---
# ---
# output: rmarkdown::html_vignette
# vignette: >
#   %\VignetteIndexEntry{"Building R Packages"}}
#   %\VignetteEngine{knitr::rmarkdown}
#   \usepackage[utf8]{inputenc}
# ---

 https://github.com/jimhester/presentations/tree/master/2018_02_03-You-can-make-a-package-in-20-minutes/#_readme  
 video:   
 https://www.rstudio.com/resources/videos/you-can-make-a-package-in-20-minutes/  

``` 
install.packages(c("devtools", "roxygen2", "testthat", "usethis"))
update.packages(ask = FALSE, checkBuilt = TRUE)
```
### Html presentation ###
 
 https://rawgit.com/jimhester/presentations/master/2018_02_03-You-can-make-a-package-in-20-minutes/2018_02_03-rstudio_conf-You_can_make_a_package_in_20_minutes.html#/
 
### References ###
 
  * R packages <r-pkgs.had.co.nz>
  *   Writing R Extensions
  * rOpenSci Onboarding
   
### POSTS ###
* Writing an R package from scratch - Hilary Parker (@hspter)
   https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch
* How to develop good R packages - Maëlle Salmon (@ma_salmon)
    http://www.masalmon.eu/2017/12/11/goodrpackages/
* Making your first R package - Fong Chun Chan (@fongchunchan)
    http://tinyheero.github.io/jekyll/update/2015/07/26/making-your-first-R-package.html
 
### Tools FOR  pkg DEVELOPMENT ###

   * DEVTOOLS / ROXYGEN2
   * USETHIS
   * R pkg COMPONENTS


### DEVTOOLS / ROXYGEN2 ###
* load_all() / install()
* test() / check()
* document()
* release() / rhub_check()

### USETHIS ###  
* create_package()  
* use_test() / use_r()  
* use_git() / use_github()  
* use_travis() / use_coverage()

### R Components ###
* Package metadata (DESCRIPTION)
* Code (R/)
* Testing (tests/)  

Less important for routine packages

* Namespaces (NAMESPACE)
* Object documentation (man/)
* Vignettes (vignettes/)
* Data (data/)
* Compiled code (src/)
* Installed files (inst/)

### Demo ###

### Create your seed function script ####

1. Create a directory "<NewPkgDir>" for your new package with subdirectory  "<NewPkgDir>/R"
2. Put your seed function file in "<NewPkgDir>/R/<mySeedFunction.R>
3. usethis::create_package("<NewPkgDir>")
4. New project opened in R script
    + Edit DESCRIPTION FILE
    + (copy seed code --- not necessary if you put mySeedFunction.R in correct directory)
    + devtools: load_all('.') \# can also do via RStudio build menu
    + devtools::check() \# Can do via RStudio build menu
    
 After check: 
 May have to clean up library statements
        + usethis:use_package('<libraryNameX>') 
        + In source file(s): 
            + remove library names in R/<source files>
            + add roxygen @importFrom for any functiouns you need to use
                @importFrom <libraryNameX> <func1> <func2>
            + add roxygen for any functions in libraries you want available             to users of package libraryNameX
                @export
                <libraryNameX>::func1
             + add roxygen @export before any functions inside the SOURCE code you want available.
             
### Adding a vignette or two ###
http://kbroman.org/pkg_primer/pages/vignettes.html


The following has been  manually scraped from kbroman.org site above.
```
To include an R Markdown document as a vignette in your R package, all you need to do is:

Create a vignettes subdirectory.
Put your .Rmd file in that directory.  
Within the YAML header at the top of the .Rmd file, include code like the following:

---
title: "Put the title of your vignette here"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Put the title of your vignette here}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---
Add the following lines to your package’s DESCRIPTION file:

Suggests: knitr, rmarkdown
VignetteBuilder: knitr
You can build your vignette with the devtools::build_vignettes() function. The resulting .html vignette will be in the inst/doc folder.
```
### Github ###
https://www.youtube.com/watch?v=E2d91v1Twcc
Steps:
Create new repository
